GET http://127.0.0.1:3000/tasks?page=1&per_page=2&include=user HTTP/1.1
Authorization: Bearer eyJhY2Nlc3MtdG9rZW4iOiJ2TmdDTHA3TVEtNWo0TWNid2lkUjJBIiwidG9rZW4tdHlwZSI6IkJlYXJlciIsImNsaWVudCI6IkVJN0FUOFQ4aVlvT2dYS1YzamlPd2ciLCJleHBpcnkiOiIxNjg3NTA5NTMwIiwidWlkIjoic2thcm1vcnlzdGVlbEBnbWFpbC5jb20ifQ==
